In [1]:
import pandas as pd
import qiime2 as q2
import biom
from biom import Table

In [2]:
# Feature table from Qiita analysis 75191
qiita_table = biom.load_table("../../data/75191_analysis_Metagenomic_Woltkav017pairedendDatabasescratchqpwoltkaWoLr2WoLr2BIOMnonebiomNA.biom")

## Drop features with lower than 1% coverage

In [3]:
# Import coverages
cov = pd.read_csv('../output_files/coverage.tsv', sep = '\t')

In [4]:
# Check how many features will be retained with a 1% threshold

len(cov[cov['percent_covered'] > 1])

2709

In [5]:
qiita_table = qiita_table.filter(cov[cov['percent_covered'] > 1]['genome_id'], axis='observation')

In [6]:
cov.loc[cov['genome_id'].isin(qiita_table.to_dataframe().index)]

        genome_id  covered   length  percent_covered
1      G000006605   271509  2476842        10.961902
4      G000006785    75514  1852433         4.076477
5      G000006845   161256  2153922         7.486622
6      G000006865  2248779  2365589        95.062118
7      G000006925  4626366  4828840        95.806985
...           ...      ...      ...              ...
12618  G902792985    39317  2605102         1.509231
12625  G902798515    12520  1021965         1.225091
12633  G902799415    33070  2361491         1.400386
12645  G902801825    12264   856791         1.431388
12646  G902801975    33388  1726758         1.933566

[2709 rows x 4 columns]

In [13]:
genomes = ['G000436455', 'G000438215', 'G000159435', 'G001042675', 'G900539185', 'G000438095', 'G900547795',
       'G001916165', 'G000155855', 'G900539325', 'G000433515',
       'G000518765', 'G000712055', 'G000421005', 'G003477605', 'G900103835', 'G001603945', 'G000434055', 'G000179635', 'G900095865']

In [14]:
cov[cov['genome_id'].isin(genomes)]

        genome_id  covered   length  percent_covered
689    G000155855  3021949  3028486        99.784150
747    G000159435   862255  1879552        45.875560
942    G000179635    78640  4482167         1.754508
2612   G000421005    36728  3045179         1.206103
2980   G000433515  2432210  2514987        96.708651
2991   G000434055  2157172  2207372        97.725802
3055   G000436455  4449307  4499379        98.887135
3096   G000438095  2988872  3016697        99.077634
3097   G000438215  3934624  3945829        99.716029
3477   G000518765    52120  3588283         1.452505
4025   G000712055    44598  4207237         1.060031
5170   G001042675  1068388  1890857        56.502845
6470   G001603945   139268  2390892         5.824939
7536   G001916165  3205271  3264077        98.198388
9038   G003477605  3056234  3109061        98.300870
11273  G900095865  2867545  2985450        96.050679
11385  G900103835    51032  2917655         1.749076
12012  G900539185  1180617  2414563        48.895680
12014  G900539325   278973  1868682        14.928864
12072  G900547795  1160065  1181808        98.160192

In [7]:
with open("../data/micov_filtered_feature-table.biom", "w") as f:
    f.write(qiita_table.to_json("Generated by script"))